version: "3"
services:
  client:
    build:
      context: "./client"
      dockerfile: Dockerfile.dev
    restart: on-failure
    volumes:
      - /app/node_modules
      - ./client:/app

  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  redis:
    image: "redis:latest"

  api:
    build:
      context: "./server"
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_POST=6379
      - PG_USER=postgres
      - PG_HOST=postgres
      - PG_DATABASE=postgres
      - PG_PASSWORD=postgres_password
      - PG_PORT=5432

  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  nginx:
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    restart: on-failure
    ports:
      - "3050:80"
